name: Build and Deploy Packages

on:
  push:
    branches:
      - main
    # schedule:
      # - cron: '0 0 * * *' # Schedule to run every day at 12 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      repository-projects: write
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    steps:
      - name: Set up Arch Linux environment
        run: |
          pacman -Syu --noconfirm
          pacman -S sudo --noconfirm
          echo -e "\n[StratOS-repo]\nSigLevel = Optional TrustAll\nServer = https://StratOS-Linux.github.io/StratOS-repo/x86_64" | sudo tee -a /etc/pacman.conf
          sudo sed -i 's/purge debug/purge !debug/g' /etc/makepkg.conf
          sudo pacman -Syy git gtk-layer-shell base-devel --needed --noconfirm # gtk-update-icon-cache fd wget ninja qt6-tools base-devel cmake fakeroot github-cli extra-cmake-modules --needed --noconfirm
          git clone https://github.com/StratOS-Linux/StratOS-repo 
          


      - name: Create dummy user for makepkg
        run: |
            sudo useradd -m builder -s /bin/bash
            sudo usermod -aG wheel builder
            echo '%wheel ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers
            echo "Keys!"
            sudo -u builder curl -sS https://github.com/elkowar.gpg | gpg --import --yes -
            sudo -u builder curl -sS https://github.com/web-flow.gpg | gpg --import --yes -
            # echo "GPG!"
            # sudo -u builder gpg --recv-keys 862BA3D7D7760F13

      - name: GPG
        run: |
            sudo sed -e 's/#PACKAGER="John Doe <john@doe.com>"/PACKAGER="ZeStig <zestig@duck.com>"/' -e 's/#GPGKEY=""/GPGKEY="90D63B3FE2F217ED"/' -i /etc/makepkg.conf
            sudo pacman-key --init
            sudo pacman-key --populate archlinux
            sudo pacman-key --recv-keys 90D63B3FE2F217ED
            sudo pacman-key --lsign-key 90D63B3FE2F217ED
            cat /etc/makepkg.conf
            sudo -u builder gpg --recv-keys 90D63B3FE2F217ED


      - name: Trust GPG key
        run: |
            # gpg --edit-key 90D63B3FE2F217ED
            # trust
            # 5  # Select trust level (5 is ultimate trust, adjust as needed)
            # y  # Confirm trust setting
            # quit
            echo "5" | gpg --batch --passphrase "" --yes --command-fd 0 --edit-key 90D63B3FE2F217ED trust quit

      - name: Build and package software
        run: |  
          dir="$(pwd)"/StratOS-repo
          # sudo pacman -U $dir/x86_64/ckbcomp-1.227-1-any.pkg.tar.zst --noconfirm # for now
                               
          # git clone https://aur.archlinux.org/kpmcore-git                    
          # sudo chmod -R 777 ./kpmcore-git                                    
          # cd kpmcore-git                                                     
          # sudo -u builder makepkg --sign -crfs --noconfirm                           
          # rm -f **debug**.pkg.tar.zst                 
          # cp *.pkg.tar.zst $dir/x86_64/                                      
          # cp PKGBUILD $dir/PKGBUILDS/kpmcore-git/PKGBUILD
          # sudo pacman -U *.pkg.tar.zst --noconfirm                           
          # cd ..                                                              
          # rm -rf kpmcore-git

          PACKAGES=(
            # "albert" 
            # "aurutils" 
            # "bibata-cursor-theme-bin"
            # "calamares-git" 
            # "eww"
            # "gruvbox-plus-icon-theme-git" 
            # "libadwaita-without-adwaita-git" 
            # "mkinitcpio-openswap" 
            # "nwg-dock-hyprland" 
            # "pandoc-bin" 
            # "ventoy-bin" 
            "yay-bin"
          )

          # cd $dir/PKGBUILDS/rockers/; sudo chmod -R 777 ../rockers; sudo -u builder makepkg --sign -crfs --noconfirm; rm -f **debug**.pkg.tar.zst; mv *.pkg.tar.zst $dir/x86_64/; cd $dir/

          for i in "${PACKAGES[@]}"; do
              git clone https://aur.archlinux.org/$i
              sudo chmod -R 777 ./$i
              cd $i
              cp PKGBUILD $dir/PKGBUILDS/$i/PKGBUILD
              sudo -u builder makepkg --sign -crfs --noconfirm
              rm -rf $dir/x86_64/"$i"**.pkg.tar.zst**
              mv *.pkg.tar.zst** $dir/x86_64/
              cd ..
              rm -rf $i
          done

      - name: Initialize and push
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            dir="$(pwd)"/StratOS-repo
            cd $dir
            repo-add -Rn -sv x86_64/StratOS-repo.db.tar.gz x86_64/*.pkg.tar.zst
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -am "Update packages"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/StratOS-Linux/StratOS-repo.git"


  website:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: ./_site

  deploy:
    permissions: 
      id-token: write
      contents: write
      pull-requests: write
      repository-projects: write
      pages: write
    needs: website
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
