name: Build packages

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'  # Schedule to run every day at 12 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      repository-projects: write
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    steps:

      - name: Set up Arch Linux environment
        run: |
          pacman -Syu --noconfirm
          pacman -S sudo --noconfirm
          echo -e "\n[StratOS-repo]\nSigLevel = Optional TrustAll\nServer = https://StratOS-Linux.github.io/StratOS-repo/x86_64" | sudo tee -a /etc/pacman.conf
          sudo sed -i 's/purge debug/purge !debug/g' /etc/makepkg.conf
          sudo pacman -Syy git python-clickgen gtk-update-icon-cache fd wget ninja qt6-tools base-devel cmake fakeroot github-cli extra-cmake-modules --needed --noconfirm
          # sudo ckbcomp pacman -S yaml-cpp boost qt5-base qt5-declarative hwinfo python-jsonschema python-yaml solid squashfs-tools qt5-quickcontrols2 qt5-svg qt5-tools qt5-translations qt5-webengine libpwquality libyaml kpmcore kcoreaddons ki18n kconfig kservice kwidgetsaddons kiconthemes kitemviews kxmlgui kbookmarks kcompletion --needed --noconfirm
          git clone https://github.com/StratOS-Linux/StratOS-repo 

      - name: Create dummy user for makepkg
        run: |
            sudo useradd -m builder -s /bin/bash
            sudo usermod -aG wheel builder
            echo '%wheel ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers

      - name: Build and package software
        run: |  
          dir="$(pwd)"/StratOS-repo
          # echo Dir is $dir
          # ls $dir
          # rm -rf $dir/x86_64
          # mkdir -p $dir/x86_64
          sudo pacman -U $dir/x86_64/ckbcomp-1.227-1-any.pkg.tar.zst --noconfirm # for now

          # Build Rockers
          cd $dir/PKGBUILDS/rockers/
          makepkg -scf --noconfirm
          rm -rf ./rockers-debug-*
          # sudo pacman -U ./rockers*.pkg.tar.zst -- noconfirm
          mv ./rockers*.pkg.tar.zst $dir/x86_64/

          # Build kpmcore first (Calamares)                                  
          git clone https://aur.archlinux.org/kpmcore-git                    
          sudo chmod -R 777 ./kpmcore-git                                    
          cd kpmcore-git                                                     
          sudo -u builder makepkg -cfs --noconfirm                           
          rm -f **debug**.pkg.tar.zst                 
          cp *.pkg.tar.zst $dir/x86_64/                                      
          cp PKGBUILD $dir/PKGBUILDS/kpmcore-git/PKGBUILD
          sudo pacman -U *.pkg.tar.zst --noconfirm                           
          cd ..                                                              
          rm -rf kpmcore-git    
          # import some GPG keys for EWW
          # curl -sS https://github.com/elkowar.gpg | gpg --import --batch --yes -
          # curl -sS https://github.com/web-flow.gpg | gpg --import --batch --yes -


          PACKAGES=(
            "albert" 
            "aurutils" 
            "bibata-cursor-theme" 
            "calamares-git" 
            # "eww"
            "gruvbox-plus-icon-theme-git" 
            "libadwaita-without-adwaita-git" 
            "mkinitcpio-openswap" 
            "nwg-dock-hyprland" 
            "pandoc-bin" 
            "python-clickgen" 
            # "swayosd-git" 
            "ventoy-bin" 
            "yay-bin"
          )

          for i in "${PACKAGES[@]}"; do
              git clone https://aur.archlinux.org/$i
              sudo chmod -R 777 ./$i
              cd $i
              cp PKGBUILD $dir/PKGBUILDS/$i/PKGBUILD
              sudo -u builder makepkg -cfs --noconfirm
              mv *.pkg.tar.zst $dir/x86_64/
              cd ..
              rm -rf $i
          done
          mv /tmp/*ckbcomp* $dir/x86_64/

      - name: Initialize and push
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            dir="$(pwd)"/StratOS-repo
            cd $dir
            # chmod +x ./initialize.sh
            bash ./initialize.sh
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -am "Update packages"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/StratOS-Linux/StratOS-repo.git"
